wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1677577979.56665
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.7.15
      5: 0.13.10
      8:
      - 5
alpha:
  desc: null
  value: 0.5
cuda:
  desc: null
  value: true
dilation:
  desc: null
  value: 10
entropy_coef:
  desc: null
  value: 1.0e-05
env_max_step:
  desc: null
  value: 100
env_name:
  desc: null
  value: MiniGrid-FourRooms-v0
eps:
  desc: null
  value: 0.0001
gamma_m:
  desc: null
  value: 0.99
gamma_w:
  desc: null
  value: 0.9
grad_clip:
  desc: null
  value: 1.0
grid_size:
  desc: null
  value: 19
hidden_dim_manager:
  desc: null
  value: 64
hidden_dim_worker:
  desc: null
  value: 32
lr:
  desc: null
  value: 9.999999999999999e-06
max_steps:
  desc: null
  value: 1000000
mlp:
  desc: null
  value: 1
num_steps:
  desc: null
  value: 100
num_workers:
  desc: null
  value: 16
reward_reg:
  desc: null
  value: 1
run_name:
  desc: null
  value: baseline
seed:
  desc: null
  value: 0
time_horizon:
  desc: null
  value: 10
whole:
  desc: null
  value: 1
